---
- hosts: local
  become: true
  tasks:
  - name: Ensure NTP (for time synchronization) is installed.
    yum: name=ntp state=present
  - name: Enuse NTP is running.
    service: name=ntpd state=started enabled=yes
