---
- hosts: all
  gather_facts: no
  tasks:
    - name: shutdown
      command: "/sbin/shutdown -h now"
      become: true

    - name: wait go down
      local_actionwait_for host={{ ansible_ssh_host }} port=22 state=stopped
